spring.application.name=airbooking
# Server
server.port=8080

# DATASOURCE (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.schema=public

# JPA / Hibernate
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.jedis.pool.time-between-eviction-runs=10m
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.acks=all
spring.kafka.producer.retries=2147483647

spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

spring.kafka.producer.properties.linger.ms=5
spring.kafka.producer.properties.batch.size=32768

# Outbox
outbox.scheduler.delay=10000
outbox.scheduler.cron=0 0 * * * *

# Observability
management.endpoints.web.exposure.include=health,metrics,prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.service_method_latency=true


# Info
info.app.name=AirBookingPetProject
info.app.version=1.0.0
info.app.description=Spring Boot pet project