spring.application.name=airbooking
# Server
server.port=8080

# DATASOURCE (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.schema=public

# JPA / Hibernate
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.jedis.pool.time-between-eviction-runs=10m

# Info
info.app.name=AirBookingPetProject
info.app.version=1.0.0
info.app.description=Spring Boot pet project